
// This file has been generated by the GUI designer. Do not modify.
namespace EMUlsifier
{
	public partial class AddEmulatorWindow
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget EMUlsifier.AddEmulatorWindow
			this.Name = "EMUlsifier.AddEmulatorWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("EMUlsifier - Add New Emulator");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
