
// This file has been generated by the GUI designer. Do not modify.
namespace EMUlsifier
{
	public partial class EmulatorDialog
	{
		private global::Gtk.HBox hbox1;
		private global::Gtk.Image image1;
		private global::Gtk.Alignment alignment1;
		private global::Gtk.VBox vbox2;
		private global::Gtk.Label label1;
		private global::Gtk.Label label2;
		private global::Gtk.HSeparator hseparator1;
		private global::Gtk.Frame frame1;
		private global::Gtk.Alignment GtkAlignment2;
		private global::Gtk.Entry EmulatorNameEntry;
		private global::Gtk.Label GtkLabel2;
		private global::Gtk.Frame frame6;
		private global::Gtk.Alignment GtkAlignment9;
		private global::Gtk.ComboBox SystemTypeCombo;
		private global::Gtk.Label GtkLabel9;
		private global::Gtk.Frame frame2;
		private global::Gtk.Alignment GtkAlignment3;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Entry EmulatorPathEntry;
		private global::Gtk.Button button110;
		private global::Gtk.Label GtkLabel3;
		private global::Gtk.Frame frame3;
		private global::Gtk.Alignment GtkAlignment5;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Entry EmulatorLaunchArgsEntry;
		private global::Gtk.Label label3;
		private global::Gtk.Label GtkLabel5;
		private global::Gtk.Frame frame4;
		private global::Gtk.Alignment GtkAlignment6;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Entry RomPathEntry;
		private global::Gtk.Button button119;
		private global::Gtk.Label GtkLabel6;
		private global::Gtk.Frame frame5;
		private global::Gtk.Alignment GtkAlignment8;
		private global::Gtk.VBox vbox4;
		private global::Gtk.Entry RomMaskEntry;
		private global::Gtk.Label label4;
		private global::Gtk.Label GtkLabel8;
		private global::Gtk.Button AddEmulatorButton;
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget EMUlsifier.EmulatorDialog
			this.Name = "EMUlsifier.EmulatorDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Add/Update Emulator");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.BorderWidth = ((uint)(10));
			this.Resizable = false;
			this.AllowGrow = false;
			// Internal child EMUlsifier.EmulatorDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.image1 = new global::Gtk.Image ();
			this.image1.Name = "image1";
			this.image1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("EMUlsifier.icons.1388104318_Streamline-15.png");
			this.hbox1.Add (this.image1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.image1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (0F, 0.5F, 1F, 1F);
			// Container child alignment1.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 0F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><big>Emulator</big></b>");
			this.label1.UseMarkup = true;
			this.vbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("<span foreground=\"grey\">Add/Update an emulator</span>");
			this.label2.UseMarkup = true;
			this.vbox2.Add (this.label2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label2]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.alignment1.Add (this.vbox2);
			this.hbox1.Add (this.alignment1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.alignment1]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			w1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(w1 [this.hbox1]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			w1.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(w1 [this.hseparator1]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			w8.Padding = ((uint)(6));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.EmulatorNameEntry = new global::Gtk.Entry ();
			this.EmulatorNameEntry.CanFocus = true;
			this.EmulatorNameEntry.Name = "EmulatorNameEntry";
			this.EmulatorNameEntry.IsEditable = true;
			this.EmulatorNameEntry.InvisibleChar = '●';
			this.GtkAlignment2.Add (this.EmulatorNameEntry);
			this.frame1.Add (this.GtkAlignment2);
			this.GtkLabel2 = new global::Gtk.Label ();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("Name:");
			this.frame1.LabelWidget = this.GtkLabel2;
			w1.Add (this.frame1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(w1 [this.frame1]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.frame6 = new global::Gtk.Frame ();
			this.frame6.Name = "frame6";
			this.frame6.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame6.Gtk.Container+ContainerChild
			this.GtkAlignment9 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment9.Name = "GtkAlignment9";
			this.GtkAlignment9.LeftPadding = ((uint)(12));
			// Container child GtkAlignment9.Gtk.Container+ContainerChild
			this.SystemTypeCombo = global::Gtk.ComboBox.NewText ();
			this.SystemTypeCombo.Name = "SystemTypeCombo";
			this.GtkAlignment9.Add (this.SystemTypeCombo);
			this.frame6.Add (this.GtkAlignment9);
			this.GtkLabel9 = new global::Gtk.Label ();
			this.GtkLabel9.Name = "GtkLabel9";
			this.GtkLabel9.LabelProp = global::Mono.Unix.Catalog.GetString ("System Type:");
			this.frame6.LabelWidget = this.GtkLabel9;
			w1.Add (this.frame6);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(w1 [this.frame6]));
			w14.Position = 3;
			w14.Expand = false;
			w14.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.EmulatorPathEntry = new global::Gtk.Entry ();
			this.EmulatorPathEntry.Sensitive = false;
			this.EmulatorPathEntry.CanFocus = true;
			this.EmulatorPathEntry.Name = "EmulatorPathEntry";
			this.EmulatorPathEntry.IsEditable = true;
			this.EmulatorPathEntry.InvisibleChar = '●';
			this.hbox2.Add (this.EmulatorPathEntry);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.EmulatorPathEntry]));
			w15.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button110 = new global::Gtk.Button ();
			this.button110.CanFocus = true;
			this.button110.Name = "button110";
			this.button110.UseUnderline = true;
			this.button110.Label = global::Mono.Unix.Catalog.GetString ("_Browse...");
			global::Gtk.Image w16 = new global::Gtk.Image ();
			w16.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-open", global::Gtk.IconSize.Menu);
			this.button110.Image = w16;
			this.hbox2.Add (this.button110);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button110]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			this.GtkAlignment3.Add (this.hbox2);
			this.frame2.Add (this.GtkAlignment3);
			this.GtkLabel3 = new global::Gtk.Label ();
			this.GtkLabel3.Name = "GtkLabel3";
			this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString ("Executable Path:");
			this.frame2.LabelWidget = this.GtkLabel3;
			w1.Add (this.frame2);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(w1 [this.frame2]));
			w20.Position = 4;
			w20.Expand = false;
			w20.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.frame3 = new global::Gtk.Frame ();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment5 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment5.Name = "GtkAlignment5";
			this.GtkAlignment5.LeftPadding = ((uint)(12));
			// Container child GtkAlignment5.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.EmulatorLaunchArgsEntry = new global::Gtk.Entry ();
			this.EmulatorLaunchArgsEntry.CanFocus = true;
			this.EmulatorLaunchArgsEntry.Name = "EmulatorLaunchArgsEntry";
			this.EmulatorLaunchArgsEntry.IsEditable = true;
			this.EmulatorLaunchArgsEntry.InvisibleChar = '●';
			this.vbox3.Add (this.EmulatorLaunchArgsEntry);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.EmulatorLaunchArgsEntry]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("<span foreground=\"grey\">Use %ROM% in place of rom file path</span>");
			this.label3.UseMarkup = true;
			this.vbox3.Add (this.label3);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label3]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			this.GtkAlignment5.Add (this.vbox3);
			this.frame3.Add (this.GtkAlignment5);
			this.GtkLabel5 = new global::Gtk.Label ();
			this.GtkLabel5.Name = "GtkLabel5";
			this.GtkLabel5.LabelProp = global::Mono.Unix.Catalog.GetString ("Launch Arguments:");
			this.frame3.LabelWidget = this.GtkLabel5;
			w1.Add (this.frame3);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(w1 [this.frame3]));
			w25.Position = 5;
			w25.Expand = false;
			w25.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.frame4 = new global::Gtk.Frame ();
			this.frame4.Name = "frame4";
			this.frame4.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame4.Gtk.Container+ContainerChild
			this.GtkAlignment6 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment6.Name = "GtkAlignment6";
			this.GtkAlignment6.LeftPadding = ((uint)(12));
			// Container child GtkAlignment6.Gtk.Container+ContainerChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.RomPathEntry = new global::Gtk.Entry ();
			this.RomPathEntry.Sensitive = false;
			this.RomPathEntry.CanFocus = true;
			this.RomPathEntry.Name = "RomPathEntry";
			this.RomPathEntry.IsEditable = true;
			this.RomPathEntry.InvisibleChar = '●';
			this.hbox3.Add (this.RomPathEntry);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.RomPathEntry]));
			w26.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.button119 = new global::Gtk.Button ();
			this.button119.CanFocus = true;
			this.button119.Name = "button119";
			this.button119.UseUnderline = true;
			this.button119.Label = global::Mono.Unix.Catalog.GetString ("_Browse...");
			global::Gtk.Image w27 = new global::Gtk.Image ();
			w27.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-open", global::Gtk.IconSize.Menu);
			this.button119.Image = w27;
			this.hbox3.Add (this.button119);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.button119]));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			this.GtkAlignment6.Add (this.hbox3);
			this.frame4.Add (this.GtkAlignment6);
			this.GtkLabel6 = new global::Gtk.Label ();
			this.GtkLabel6.Name = "GtkLabel6";
			this.GtkLabel6.LabelProp = global::Mono.Unix.Catalog.GetString ("Rom Folder Path:");
			this.frame4.LabelWidget = this.GtkLabel6;
			w1.Add (this.frame4);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(w1 [this.frame4]));
			w31.Position = 6;
			w31.Expand = false;
			w31.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.frame5 = new global::Gtk.Frame ();
			this.frame5.Name = "frame5";
			this.frame5.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame5.Gtk.Container+ContainerChild
			this.GtkAlignment8 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment8.Name = "GtkAlignment8";
			this.GtkAlignment8.LeftPadding = ((uint)(12));
			// Container child GtkAlignment8.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.RomMaskEntry = new global::Gtk.Entry ();
			this.RomMaskEntry.CanFocus = true;
			this.RomMaskEntry.Name = "RomMaskEntry";
			this.RomMaskEntry.IsEditable = true;
			this.RomMaskEntry.InvisibleChar = '●';
			this.vbox4.Add (this.RomMaskEntry);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.RomMaskEntry]));
			w32.Position = 0;
			w32.Expand = false;
			w32.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("<span foreground=\"grey\">Space-separated list of file types (e.g. .zip .iso etc.)." +
			" Leave blank to accept all files.</span>");
			this.label4.UseMarkup = true;
			this.vbox4.Add (this.label4);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label4]));
			w33.Position = 1;
			w33.Expand = false;
			w33.Fill = false;
			this.GtkAlignment8.Add (this.vbox4);
			this.frame5.Add (this.GtkAlignment8);
			this.GtkLabel8 = new global::Gtk.Label ();
			this.GtkLabel8.Name = "GtkLabel8";
			this.GtkLabel8.LabelProp = global::Mono.Unix.Catalog.GetString ("Rom File Mask:");
			this.frame5.LabelWidget = this.GtkLabel8;
			w1.Add (this.frame5);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(w1 [this.frame5]));
			w36.Position = 7;
			w36.Expand = false;
			w36.Fill = false;
			// Internal child EMUlsifier.EmulatorDialog.ActionArea
			global::Gtk.HButtonBox w37 = this.ActionArea;
			w37.Name = "dialog1_ActionArea";
			w37.Spacing = 10;
			w37.BorderWidth = ((uint)(5));
			w37.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.AddEmulatorButton = new global::Gtk.Button ();
			this.AddEmulatorButton.Sensitive = false;
			this.AddEmulatorButton.CanDefault = true;
			this.AddEmulatorButton.CanFocus = true;
			this.AddEmulatorButton.Name = "AddEmulatorButton";
			this.AddEmulatorButton.UseStock = true;
			this.AddEmulatorButton.UseUnderline = true;
			this.AddEmulatorButton.Label = "gtk-ok";
			this.AddActionWidget (this.AddEmulatorButton, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w38 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w37 [this.AddEmulatorButton]));
			w38.Expand = false;
			w38.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonOk, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w39 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w37 [this.buttonOk]));
			w39.Position = 1;
			w39.Expand = false;
			w39.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 568;
			this.DefaultHeight = 501;
			this.Show ();
			this.EmulatorNameEntry.Changed += new global::System.EventHandler (this.EmuEntryOnChange);
			this.EmulatorNameEntry.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.EmuEntryOnFocusOut);
			this.SystemTypeCombo.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.EmuEntryOnFocusOut);
			this.EmulatorPathEntry.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.EmuEntryOnFocusOut);
			this.EmulatorPathEntry.Changed += new global::System.EventHandler (this.EmuEntryOnChange);
			this.button110.Clicked += new global::System.EventHandler (this.EmulatorPathOnClick);
			this.EmulatorLaunchArgsEntry.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.EmuEntryOnFocusOut);
			this.EmulatorLaunchArgsEntry.Changed += new global::System.EventHandler (this.EmuEntryOnChange);
			this.RomPathEntry.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.EmuEntryOnFocusOut);
			this.RomPathEntry.Changed += new global::System.EventHandler (this.EmuEntryOnChange);
			this.button119.Clicked += new global::System.EventHandler (this.RomPathButtonOnClick);
			this.RomMaskEntry.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.EmuEntryOnFocusOut);
			this.RomMaskEntry.Changed += new global::System.EventHandler (this.EmuEntryOnChange);
		}
	}
}
