
// This file has been generated by the GUI designer. Do not modify.
namespace EMUlsifier
{
	public partial class IndeterminateProgressDialog
	{
		private global::Gtk.HBox hbox1;
		private global::Gtk.Image IndeterminateProgressDialogIcon;
		private global::Gtk.VBox vbox2;
		private global::Gtk.Label IndeterminateProgressMessage;
		private global::Gtk.ProgressBar IndeterminateProgressDialogBar;
		private global::Gtk.Button buttonCancel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget EMUlsifier.IndeterminateProgressDialog
			this.Name = "EMUlsifier.IndeterminateProgressDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.BorderWidth = ((uint)(6));
			this.Resizable = false;
			this.AllowGrow = false;
			this.Gravity = ((global::Gdk.Gravity)(5));
			// Internal child EMUlsifier.IndeterminateProgressDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.IndeterminateProgressDialogIcon = new global::Gtk.Image ();
			this.IndeterminateProgressDialogIcon.Name = "IndeterminateProgressDialogIcon";
			this.IndeterminateProgressDialogIcon.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-info", global::Gtk.IconSize.Dialog);
			this.hbox1.Add (this.IndeterminateProgressDialogIcon);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.IndeterminateProgressDialogIcon]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.IndeterminateProgressMessage = new global::Gtk.Label ();
			this.IndeterminateProgressMessage.Name = "IndeterminateProgressMessage";
			this.IndeterminateProgressMessage.Xalign = 0F;
			this.IndeterminateProgressMessage.Wrap = true;
			this.vbox2.Add (this.IndeterminateProgressMessage);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.IndeterminateProgressMessage]));
			w3.Position = 0;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.IndeterminateProgressDialogBar = new global::Gtk.ProgressBar ();
			this.IndeterminateProgressDialogBar.Name = "IndeterminateProgressDialogBar";
			this.IndeterminateProgressDialogBar.Text = "";
			this.vbox2.Add (this.IndeterminateProgressDialogBar);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.IndeterminateProgressDialogBar]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.hbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
			w5.Position = 1;
			w1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(w1 [this.hbox1]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Internal child EMUlsifier.IndeterminateProgressDialog.ActionArea
			global::Gtk.HButtonBox w7 = this.ActionArea;
			w7.Name = "dialog1_ActionArea";
			w7.Spacing = 10;
			w7.BorderWidth = ((uint)(5));
			w7.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w7 [this.buttonCancel]));
			w8.Expand = false;
			w8.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 481;
			this.DefaultHeight = 159;
			this.Show ();
		}
	}
}
