
// This file has been generated by the GUI designer. Do not modify.
namespace EMUlsifier
{
	public partial class GameViewWidget
	{
		private global::Gtk.ScrolledWindow GameViewScroll;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Image GameBannerImage;
		private global::Gtk.Label GameTitleLabel;
		private global::Gtk.Image GameBoxArtImage;
		private global::Gtk.TextView GameDescriptionTextView;
		private global::Gtk.Alignment alignment1;
		private global::Gtk.VBox vbox6;
		private global::Gtk.Label GameGeneresLabel;
		private global::Gtk.Label GameReleaseDateLabel;
		private global::Gtk.Label GameRatingLabel;
		private global::Gtk.Label GameDeveloperLabel;
		private global::Gtk.Label GamePublisherLabel;
		private global::Gtk.Label GameCommunityRatingLabel;
		private global::Gtk.Button button1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget EMUlsifier.GameViewWidget
			global::Stetic.BinContainer.Attach (this);
			this.WidthRequest = 800;
			this.HeightRequest = 600;
			this.Name = "EMUlsifier.GameViewWidget";
			// Container child EMUlsifier.GameViewWidget.Gtk.Container+ContainerChild
			this.GameViewScroll = new global::Gtk.ScrolledWindow ();
			this.GameViewScroll.Name = "GameViewScroll";
			this.GameViewScroll.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GameViewScroll.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport ();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.GameBannerImage = new global::Gtk.Image ();
			this.GameBannerImage.Name = "GameBannerImage";
			this.vbox3.Add (this.GameBannerImage);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GameBannerImage]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.GameTitleLabel = new global::Gtk.Label ();
			this.GameTitleLabel.Name = "GameTitleLabel";
			this.GameTitleLabel.UseMarkup = true;
			this.GameTitleLabel.Wrap = true;
			this.vbox3.Add (this.GameTitleLabel);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GameTitleLabel]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.GameBoxArtImage = new global::Gtk.Image ();
			this.GameBoxArtImage.Name = "GameBoxArtImage";
			this.vbox3.Add (this.GameBoxArtImage);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GameBoxArtImage]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			w4.Padding = ((uint)(20));
			// Container child vbox3.Gtk.Box+BoxChild
			this.GameDescriptionTextView = new global::Gtk.TextView ();
			this.GameDescriptionTextView.Sensitive = false;
			this.GameDescriptionTextView.Name = "GameDescriptionTextView";
			this.GameDescriptionTextView.Editable = false;
			this.GameDescriptionTextView.CursorVisible = false;
			this.GameDescriptionTextView.WrapMode = ((global::Gtk.WrapMode)(2));
			this.GameDescriptionTextView.LeftMargin = 20;
			this.GameDescriptionTextView.RightMargin = 20;
			this.GameDescriptionTextView.Indent = 15;
			this.vbox3.Add (this.GameDescriptionTextView);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GameDescriptionTextView]));
			w5.Position = 3;
			w5.Padding = ((uint)(10));
			// Container child vbox3.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.LeftPadding = ((uint)(30));
			this.alignment1.RightPadding = ((uint)(30));
			this.alignment1.BottomPadding = ((uint)(20));
			// Container child alignment1.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.GameGeneresLabel = new global::Gtk.Label ();
			this.GameGeneresLabel.Name = "GameGeneresLabel";
			this.GameGeneresLabel.UseMarkup = true;
			this.GameGeneresLabel.Wrap = true;
			this.vbox6.Add (this.GameGeneresLabel);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.GameGeneresLabel]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.GameReleaseDateLabel = new global::Gtk.Label ();
			this.GameReleaseDateLabel.Name = "GameReleaseDateLabel";
			this.GameReleaseDateLabel.UseMarkup = true;
			this.GameReleaseDateLabel.Wrap = true;
			this.vbox6.Add (this.GameReleaseDateLabel);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.GameReleaseDateLabel]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.GameRatingLabel = new global::Gtk.Label ();
			this.GameRatingLabel.Name = "GameRatingLabel";
			this.GameRatingLabel.UseMarkup = true;
			this.GameRatingLabel.Wrap = true;
			this.vbox6.Add (this.GameRatingLabel);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.GameRatingLabel]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.GameDeveloperLabel = new global::Gtk.Label ();
			this.GameDeveloperLabel.Name = "GameDeveloperLabel";
			this.GameDeveloperLabel.UseMarkup = true;
			this.GameDeveloperLabel.Wrap = true;
			this.vbox6.Add (this.GameDeveloperLabel);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.GameDeveloperLabel]));
			w9.Position = 3;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.GamePublisherLabel = new global::Gtk.Label ();
			this.GamePublisherLabel.Name = "GamePublisherLabel";
			this.GamePublisherLabel.UseMarkup = true;
			this.GamePublisherLabel.Wrap = true;
			this.vbox6.Add (this.GamePublisherLabel);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.GamePublisherLabel]));
			w10.Position = 4;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.GameCommunityRatingLabel = new global::Gtk.Label ();
			this.GameCommunityRatingLabel.Name = "GameCommunityRatingLabel";
			this.GameCommunityRatingLabel.UseMarkup = true;
			this.GameCommunityRatingLabel.Wrap = true;
			this.vbox6.Add (this.GameCommunityRatingLabel);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.GameCommunityRatingLabel]));
			w11.Position = 5;
			w11.Expand = false;
			w11.Fill = false;
			this.alignment1.Add (this.vbox6);
			this.vbox3.Add (this.alignment1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.alignment1]));
			w13.Position = 4;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.button1 = new global::Gtk.Button ();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString ("Launch Game");
			global::Gtk.Image w14 = new global::Gtk.Image ();
			w14.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-jump-to", global::Gtk.IconSize.LargeToolbar);
			this.button1.Image = w14;
			this.vbox3.Add (this.button1);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.button1]));
			w15.Position = 5;
			w15.Expand = false;
			w15.Fill = false;
			w15.Padding = ((uint)(20));
			w1.Add (this.vbox3);
			this.GameViewScroll.Add (w1);
			this.Add (this.GameViewScroll);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.SizeAllocated += new global::Gtk.SizeAllocatedHandler (this.GameViewOnSizeAllocated);
			this.button1.Clicked += new global::System.EventHandler (this.LaunchGameOnClick);
		}
	}
}
