
// This file has been generated by the GUI designer. Do not modify.
namespace EMUlsifier
{
	public partial class IndeterminateProgressDialog
	{
		private global::Gtk.Alignment alignment3;
		private global::Gtk.HBox hbox6;
		private global::Gtk.Image IndeterminateProgressDialogIcon;
		private global::Gtk.VBox vbox5;
		private global::Gtk.Label IndeterminateProgressMessage;
		private global::Gtk.ProgressBar IndeterminateProgressDialogBar;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget EMUlsifier.IndeterminateProgressDialog
			this.Name = "EMUlsifier.IndeterminateProgressDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(6));
			// Internal child EMUlsifier.IndeterminateProgressDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.alignment3 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment3.Name = "alignment3";
			// Container child alignment3.Gtk.Container+ContainerChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.IndeterminateProgressDialogIcon = new global::Gtk.Image ();
			this.IndeterminateProgressDialogIcon.Name = "IndeterminateProgressDialogIcon";
			this.IndeterminateProgressDialogIcon.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-info", global::Gtk.IconSize.Dialog);
			this.hbox6.Add (this.IndeterminateProgressDialogIcon);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.IndeterminateProgressDialogIcon]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.IndeterminateProgressMessage = new global::Gtk.Label ();
			this.IndeterminateProgressMessage.Name = "IndeterminateProgressMessage";
			this.vbox5.Add (this.IndeterminateProgressMessage);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.IndeterminateProgressMessage]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.IndeterminateProgressDialogBar = new global::Gtk.ProgressBar ();
			this.IndeterminateProgressDialogBar.Name = "IndeterminateProgressDialogBar";
			this.vbox5.Add (this.IndeterminateProgressDialogBar);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.IndeterminateProgressDialogBar]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.hbox6.Add (this.vbox5);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.vbox5]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.alignment3.Add (this.hbox6);
			w1.Add (this.alignment3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(w1 [this.alignment3]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Internal child EMUlsifier.IndeterminateProgressDialog.ActionArea
			global::Gtk.HButtonBox w8 = this.ActionArea;
			w8.Name = "dialog1_ActionArea";
			w8.Spacing = 10;
			w8.BorderWidth = ((uint)(5));
			w8.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w8 [this.buttonCancel]));
			w9.Expand = false;
			w9.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w8 [this.buttonOk]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 481;
			this.DefaultHeight = 159;
			this.Show ();
		}
	}
}
