
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action addAction;
	private global::Gtk.Action editAction;
	private global::Gtk.Action removeAction;
	private global::Gtk.Action refreshAction;
	private global::Gtk.Action FileAction;
	private global::Gtk.Action EditAction;
	private global::Gtk.Action HelpAction;
	private global::Gtk.Action addAction1;
	private global::Gtk.Action removeAction1;
	private global::Gtk.Action editAction1;
	private global::Gtk.Action refreshAction1;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar menubar2;
	private global::Gtk.HPaned hpaned6;
	private global::Gtk.VBox vbox4;
	private global::Gtk.Label label1;
	private global::Gtk.Toolbar toolbar1;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TreeView LibraryTreeView;
	private global::EMUlsifier.GameViewWidget GameView;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.addAction = new global::Gtk.Action ("addAction", null, null, "gtk-add");
		w1.Add (this.addAction, null);
		this.editAction = new global::Gtk.Action ("editAction", null, null, "gtk-edit");
		this.editAction.Sensitive = false;
		w1.Add (this.editAction, null);
		this.removeAction = new global::Gtk.Action ("removeAction", null, null, "gtk-remove");
		this.removeAction.Sensitive = false;
		w1.Add (this.removeAction, null);
		this.refreshAction = new global::Gtk.Action ("refreshAction", null, null, "gtk-refresh");
		this.refreshAction.Sensitive = false;
		w1.Add (this.refreshAction, null);
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.EditAction = new global::Gtk.Action ("EditAction", global::Mono.Unix.Catalog.GetString ("Edit"), null, null);
		this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edit");
		w1.Add (this.EditAction, null);
		this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.HelpAction, null);
		this.addAction1 = new global::Gtk.Action ("addAction1", null, null, "gtk-add");
		w1.Add (this.addAction1, null);
		this.removeAction1 = new global::Gtk.Action ("removeAction1", null, null, "gtk-remove");
		this.removeAction1.Sensitive = false;
		w1.Add (this.removeAction1, null);
		this.editAction1 = new global::Gtk.Action ("editAction1", null, null, "gtk-edit");
		this.editAction1.Sensitive = false;
		w1.Add (this.editAction1, null);
		this.refreshAction1 = new global::Gtk.Action ("refreshAction1", null, null, "gtk-refresh");
		this.refreshAction1.Sensitive = false;
		w1.Add (this.refreshAction1, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.DefaultWidth = 1280;
		this.DefaultHeight = 720;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name=\'menubar2\'><menu name=\'FileAction\' action=\'FileAction\'/><menu n" +
		"ame=\'EditAction\' action=\'EditAction\'/><menu name=\'HelpAction\' action=\'HelpAction" +
		"\'/></menubar></ui>");
		this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar2")));
		this.menubar2.Name = "menubar2";
		this.vbox1.Add (this.menubar2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar2]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hpaned6 = new global::Gtk.HPaned ();
		this.hpaned6.WidthRequest = 250;
		this.hpaned6.CanFocus = true;
		this.hpaned6.Name = "hpaned6";
		this.hpaned6.Position = 300;
		// Container child hpaned6.Gtk.Paned+PanedChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Library</b>");
		this.label1.UseMarkup = true;
		this.vbox4.Add (this.label1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label1]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name=\'toolbar1\'><toolitem name=\'addAction\' action=\'addAction\'/><tool" +
		"item name=\'removeAction\' action=\'removeAction\'/><toolitem name=\'editAction\' acti" +
		"on=\'editAction\'/><toolitem name=\'refreshAction\' action=\'refreshAction\'/></toolba" +
		"r></ui>");
		this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
		this.toolbar1.Name = "toolbar1";
		this.toolbar1.ShowArrow = false;
		this.vbox4.Add (this.toolbar1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.toolbar1]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.LibraryTreeView = new global::Gtk.TreeView ();
		this.LibraryTreeView.CanFocus = true;
		this.LibraryTreeView.Name = "LibraryTreeView";
		this.LibraryTreeView.EnableSearch = false;
		this.LibraryTreeView.HeadersVisible = false;
		this.GtkScrolledWindow.Add (this.LibraryTreeView);
		this.vbox4.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.GtkScrolledWindow]));
		w6.Position = 2;
		this.hpaned6.Add (this.vbox4);
		global::Gtk.Paned.PanedChild w7 = ((global::Gtk.Paned.PanedChild)(this.hpaned6 [this.vbox4]));
		w7.Resize = false;
		// Container child hpaned6.Gtk.Paned+PanedChild
		this.GameView = new global::EMUlsifier.GameViewWidget ();
		this.GameView.WidthRequest = 800;
		this.GameView.HeightRequest = 600;
		this.GameView.Events = ((global::Gdk.EventMask)(256));
		this.GameView.Name = "GameView";
		this.hpaned6.Add (this.GameView);
		this.vbox1.Add (this.hpaned6);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hpaned6]));
		w9.Position = 1;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.addAction.Activated += new global::System.EventHandler (this.AddEmulatorOnActivate);
		this.editAction.Activated += new global::System.EventHandler (this.EditButtonOnActivate);
		this.removeAction.Activated += new global::System.EventHandler (this.RemoveEmulatorButtonOnActivate);
		this.refreshAction.Activated += new global::System.EventHandler (this.ScrapeGameOnActivate);
		this.LibraryTreeView.CursorChanged += new global::System.EventHandler (this.EmulatorOnCursorChange);
	}
}
